changes

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -3,20 +3,14 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-#rsync -av --delete fin:.config/znc/ $HOME/.config/znc/ || echo "Could not copy from fin"
-
 quickping 192.168.1.65 && push -h vulcan hermes || echo "Could not push to hermes"
+quickping 192.168.1.80 && push -h vulcan athena || echo "Could not push to athena"
+quickping 192.168.1.80 && push -h vulcan tank || echo "Could not push to tank"
 
-push -h vulcan fin || echo "Could not push to fin"
-push -h vulcan tank || echo "Could not push to tank"
-
-# if ssh fin test -d /Volumes/tank/Backups; then
+# if ssh athena test -d /Volumes/tank/Backups; then
 #     push tank || echo "Could not push to tank"
-#     ssh fin b2-sync /Volumes/tank tank || echo "Could not push to Backblaze"
+#     ssh athena b2-sync /Volumes/tank tank || echo "Could not push to Backblaze"
 # fi
 
 # reindex-mail
 # recollindex
-
-# quickping 192.168.1.65 && push hermes || echo "Could not push to hermes"
-# push fin || echo "Could not push to fin"
