changes

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -3,14 +3,14 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-push hermes || echo "Could not push to hermes"
+#push hermes || echo "Could not push to hermes"
 push fin || echo "Could not push to fin"
 
 if [[ -d /Volumes/vault/Documents ]]; then
     push vault || echo "Could not push to vault"
 
-elif ssh hermes test -d /Volumes/vault/Documents; then
-    ssh hermes push vault || echo "Could not push to vault"
+#elif ssh hermes test -d /Volumes/vault/Documents; then
+#    ssh hermes push vault || echo "Could not push to vault"
 fi
 
 # if test -d /Volumes/slim/src; then
@@ -36,5 +36,5 @@ reindex-mail
 
 recollindex
 
-push hermes || echo "Could not push to hermes"
+#push hermes || echo "Could not push to hermes"
 push fin || echo "Could not push to fin"
