changes

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# quickping $HERMES_ETHERNET && \
-#     time push hermes || echo "Could not push to hermes"
+quickping $HERMES_ETHERNET && \
+    time push hermes || echo "Could not push to hermes"
 
 if [[ -d /Volumes/tank/src/pushme ]]; then
     time push tank || echo "Could not push to tank"
