changes

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -25,25 +25,26 @@ monitor "reindex-mail" reindex-mail
 # fi
 # monitor "recollindex" recollindex -z
 
-monitor "update-kadena"  update ~/kadena
-monitor "update-src"     update ~/src
+monitor "update-kadena" update ~/kadena
+monitor "update-src"    update ~/src
+monitor "update-doc"    update ~/doc
 
 if quickping $HERMES_ETHERNET; then
-    monitor "nix-update" u vulcan update-sync
+    monitor "nix-update-sync" u vulcan update-sync
 else
-    monitor "nix-update" u vulcan update
+    monitor "nix-update"      u vulcan update
 fi
 
 if quickping $HERMES_ETHERNET; then
-    monitor "travel-ready" travel-ready-all
+    monitor "travel-ready-all" u vulcan travel-ready-all
 else
-    monitor "travel-ready" travel-ready
+    monitor "travel-ready"     u vulcan travel-ready
 fi
 
 if quickping $HERMES_ETHERNET; then
     monitor "nix-check-all" u vulcan check-all
 else
-    monitor "nix-check" u vulcan check
+    monitor "nix-check"     u vulcan check
 fi
 
-gpg --refresh-keys || exit 0
+gpg --refresh-keys || echo "gpg --refresh-keys FAILED!"
