New files

diff --git a/clangup b/clangup
--- a/clangup
+++ b/clangup
@@ -8,17 +8,25 @@ if [[ "$1" == "-s" ]]; then
     shift 1
 fi
 
+nopull=false
+if [[ "$1" == "-n" ]]; then
+    nopull=true
+    shift 1
+fi
+
 if [[ -n "$1" ]]; then
     ROOT=$HOME/src/llvm/branches/$1
 else
     ROOT=$HOME/src/llvm
 fi
 
-if quickping bite.entic.net; then
-    cd $ROOT && git pull
-    cd tools/clang && git pull
-    if [[ -d test/Embt ]]; then
-        cd test/Embt && git pull
+if [[ $nopull == false ]]; then
+    if quickping bite.entic.net; then
+        cd $ROOT && git pull
+        cd tools/clang && git pull
+        if [[ -d test/Embt ]]; then
+            cd test/Embt && git pull
+        fi
     fi
 fi
 
@@ -37,11 +45,11 @@ fi
 if ! nice -n 20 make-distcc; then
     echo "Clang failed to build"
     exit 1
-else
-    if ! nice -n 20 make clang-test; then
-        echo "Clang failed tests"
-        exit 2
-    fi
+elif ! nice -n 20 make clang-test; then
+    echo "Clang failed tests"
+    exit 2
 fi
 
 exit 0
+
+### clangup ends here
