changes

diff --git a/pushme b/pushme
--- a/pushme
+++ b/pushme
@@ -20,22 +20,35 @@
 # This makes for four separate synchronization passes, for each combination.
 
 RSYNC='sudo /opt/local/bin/rsync'
-FLAGS="-arPXHEyzh"
-LAPTOP=hermes
-
-EXCLUDES=""
-EXCLUDES="$EXCLUDES --exclude=/.com.apple.timemachine.supported"
+EXCLUDES="--exclude=/.com.apple.timemachine.supported"
 EXCLUDES="$EXCLUDES --exclude=/.fseventsd/"
 EXCLUDES="$EXCLUDES --exclude=/.Spotlight-V100/"
 EXCLUDES="$EXCLUDES --exclude=/.TemporaryItems/"
 EXCLUDES="$EXCLUDES --exclude=/.Trashes/"
 EXCLUDES="$EXCLUDES --exclude=.DS_Store"
 EXCLUDES="$EXCLUDES --exclude=.localized"
-FLAGS="$FLAGS $EXCLUDES"
+FLAGS="$1 -arPXHEyzh $EXCLUDES"
 
-if [[ $(basename "$0") == 'pushme' ]]; then
+LOCAL=$(hostname -s)
+
+if [[ $LOCAL == 'Vulcan' ]]; then
+    REMOTE=hermes
+else
+    REMOTE=johnw.homeunix.net
+fi
+
+MODE=$(basename "$0")
+
+if [[ $MODE == 'pushme' ]]; then
     SOURCE=''
-    TARGET="$LAPTOP:"
+    TARGET="$REMOTE:"
+else
+    SOURCE="$REMOTE:"
+    TARGET=''
+fi
+
+if [[ ( $MODE == 'pushme'  && $REMOTE == 'hermes' ) || \
+      ( $MODE == 'pullyou' && $REMOTE != 'hermes' ) ]]; then
     SSOURCE="$SOURCE$HOME"
     TTARGET="$TARGET/Volumes/Passport"
     CSOURCE="$SOURCE$HOME/Contracts"
@@ -47,8 +60,6 @@ if [[ $(basename "$0") == 'pushme' ]]; then
     RPSOURCE="$SOURCE/Volumes/RAID"
     RPTARGET="$TARGET/Volumes/Private"
 else
-    SOURCE="$LAPTOP:"
-    TARGET=''
     SSOURCE="$SOURCE/Volumes/Passport"
     TTARGET="$TARGET$HOME"
     CSOURCE="$SOURCE/Volumes"
@@ -61,14 +72,15 @@ else
     RPTARGET="$TARGET/Volumes/RAID"
 fi
 
-if ! ssh $LAPTOP true; then
+if ! ssh $REMOTE true; then
+    echo "Error: Could not reach host $REMOTE"
     exit 1
 fi
 
 # Home: ~ <-> ~
 
 echo $SOURCE$HOME/ '->' $TARGET$HOME/
-rsync $FLAGS --delete --rsync-path "$RSYNC" \
+rsync $FLAGS --delete --rsync-path="$RSYNC" \
     --include='/.MacOSX/' \
     --include='/.PySolFC/' \
     --include='/.bazaar/' \
@@ -94,7 +106,6 @@ rsync $FLAGS --delete --rsync-path "$RSYNC" \
     --exclude='/.*' \
     --include='/Library/Application Support/' \
     --include='/Library/Audio/' \
-    --include='/Library/Calendars/' \
     --include='/Library/Emacs/' \
     --include='/Library/FontCollections/' \
     --include='/Library/Fonts/' \
@@ -150,7 +161,7 @@ rsync $FLAGS --delete --rsync-path "$RSYNC" \
 # Home: ~ <-> Private
 
 echo $PSOURCE/ '->' $PTARGET/
-rsync $FLAGS --delete --rsync-path "$RSYNC" \
+rsync $FLAGS --delete --rsync-path="$RSYNC" \
     --include='/.Deskzilla/' \
     --include='/.datastudio/' \
     --include='/.dbvis/' \
@@ -168,6 +179,7 @@ rsync $FLAGS --delete --rsync-path "$RSYNC" \
     --include='/Library/Application Support/' \
     --include='/Library/Mail/' \
     --include='/Library/Mail Downloads/' \
+    --include='/Library/Safari/' \
     --exclude='/Library/*/' \
     --exclude='/Library/*' \
     --exclude='/Library/.*/' \
@@ -192,7 +204,7 @@ rsync $FLAGS --delete --rsync-path "$RSYNC" \
 # Home: ~ and RAID (Archives is the only thing)
 
 echo $RSOURCE/ '->' $RTARGET/
-rsync $FLAGS --delete --rsync-path "$RSYNC" \
+rsync $FLAGS --delete --rsync-path="$RSYNC" \
     --include='/Archives/' \
     --exclude='/Archives/Games/' \
     --exclude='/Archives/Games' \
@@ -212,7 +224,7 @@ rsync $FLAGS --delete --rsync-path "$RSYNC" \
 # Home: Private and RAID
 
 echo $RPSOURCE/ '->' $RPTARGET/
-rsync $FLAGS --delete --rsync-path "$RSYNC" \
+rsync $FLAGS --delete --rsync-path="$RSYNC" \
     --include='/Backups/' \
     --exclude='/Backups/[0-9]*/' \
     --include='/Documents/' \
@@ -228,9 +240,13 @@ rsync $FLAGS --delete --rsync-path "$RSYNC" \
 
 for contract in CEG TI
 do
-    if ssh hermes "mount | grep -q '/Volumes/$contract.*hfs'"; then
+    if ([[ $REMOTE == 'hermes' ]] && \
+        ssh $REMOTE "mount | grep -q '/Volumes/$contract.*hfs'") || \
+       ([[ $REMOTE != 'hermes' ]] && \
+        mount | grep -q "/Volumes/$contract.*hfs")
+    then
 	echo $CSOURCE/$contract/ '->' $CTARGET/$contract/
-	rsync $FLAGS --delete --rsync-path "$RSYNC" \
+	rsync $FLAGS --delete --rsync-path="$RSYNC" \
 	    --exclude='Backup/' \
 	    --exclude='Backup.[0-9]/' \
 	    --exclude=/.backups/ \
@@ -242,16 +258,17 @@ do
     fi
 done
 
-if [[ $(basename "$0") == 'pullyou' ]]; then
+if [[ ($MODE == 'pullyou' && $REMOTE == 'hermes') || \
+      ($MODE == 'pushme'  && $REMOTE != 'hermes') ]]; then
     # Downloads
     echo $SOURCE$HOME/Downloads/ '->' $TARGET$HOME/Downloads/
-    rsync $FLAGS --rsync-path "$RSYNC" \
+    rsync $FLAGS --rsync-path="$RSYNC" \
 	$SOURCE$HOME/Downloads/ $TARGET$HOME/Downloads/
 
 else
     ## Applications
     echo $SOURCE/Applications/ '->' $TARGET/Applications/
-    rsync $FLAGS --delete --rsync-path "$RSYNC" \
+    rsync $FLAGS --delete --rsync-path="$RSYNC" \
 	--include='/Games/' \
 	--include='/Misc/' \
 	--exclude='/Misc/Networking/Dropbox.app/' \
@@ -263,7 +280,7 @@ else
 
     # opt
     echo $SOURCE/opt/local/var/macports/ '->' $TARGET/opt/local/var/macports/
-    rsync $FLAGS --delete --rsync-path "$RSYNC" \
+    rsync $FLAGS --delete --rsync-path="$RSYNC" \
 	--exclude=.tclpackage \
 	--exclude=/build/ \
 	--exclude=/port-help.tcl \
@@ -275,13 +292,15 @@ fi
 
 # stow
 echo $SOURCE/usr/local/stow/ '->' $TARGET/usr/local/stow/
-rsync $FLAGS --delete --rsync-path "$RSYNC" \
+rsync $FLAGS --delete --rsync-path="$RSYNC" \
     $SOURCE/usr/local/stow/ $TARGET/usr/local/stow/
 
-if ssh $LAPTOP test -d /Volumes/Passport; then
+if ([[ $REMOTE == 'hermes' ]] && ssh $REMOTE test -d /Volumes/Passport) || \
+   ([[ $REMOTE != 'hermes' ]] && test -d /Volumes/Passport)
+then
     # Archives, the larger part
     echo $SSOURCE/Archives/ '->' $TTARGET/Archives/
-    rsync $FLAGS --delete --rsync-path "$RSYNC" \
+    rsync $FLAGS --delete --rsync-path="$RSYNC" \
 	--include=/Linux/ \
 	--exclude=/Linux/Fedora/ \
 	--exclude=/Linux/Debian/ \
@@ -290,6 +309,6 @@ if ssh $LAPTOP test -d /Volumes/Passport; then
 
     # Media: Movies, Pictures, Photos
     echo /Volumes/RAID/Media/ '->' $TTARGET/Media/
-    rsync $FLAGS --delete --rsync-path "$RSYNC" \
+    rsync $FLAGS --delete --rsync-path="$RSYNC" \
 	/Volumes/RAID/Media/ $TTARGET/Media/
 fi
