Updated my verify script

diff --git a/verify b/verify
--- a/verify
+++ b/verify
@@ -1,11 +1,7 @@
 #!/bin/bash
 
-# verify, version 1.0
+# verify, version 2.0
 #   by John Wiegley <johnw@newartisans.com>
-
-function sha1() {
-    openssl sha1 "$1" | sed 's/.*= //'
-}
 
 if [[ -z "$1" ]]; then
     echo "usage: verify [OPTIONS] <FILE ...>"
@@ -19,12 +15,17 @@ fi
 export ATTRNAME=checksum-sha1
 
 export verbose=false
+export veryverbose=false
 export setonly=false
 export force=false
 
 while [[ "${1:0:1}" == "-" ]]; do
     if [[ "$1" == "-v" ]]; then
         export verbose=true
+        shift 1
+    elif [[ "$1" == "-vv" ]]; then
+        export verbose=true
+        export veryverbose=true
         shift 1
     elif [[ "$1" == "-s" ]]; then
         export setonly=true
@@ -39,92 +40,150 @@ done
 
 error=false
 
+function sha1() {
+    openssl sha1 "$1" | sed 's/.*= //'
+}
+
 function compare_checksum() 
 {
     CHKSUM=$(xattr -p ${ATTRNAME} "$1" 2> /dev/null)
 
     if [[ -z "$CHKSUM" ]]; then
-	if [[ $verbose == true || $setonly == true ]]; then
-	    echo "Note: No existing checksum for $1, setting..."
+	if [[ $setonly == true ]]; then
+	    echo -n "Setting:  $1..."
+
+	    CURSUM=$(sha1 "$1")
+	    xattr -w ${ATTRNAME} $CURSUM "$1"
+
+            case "$1" in
+    		*.dmg|*.cdr|*.iso|*.sparseimage)
+    	            hdiutil checksum -quiet -type SHA1 "$1" ;;
+            esac
+
+	    echo "done"
+	elif [[ $verbose == true ]]; then
+	    echo "SKIPPING: $1"
 	fi
-	CURSUM=$(sha1 "$1")
-	xattr -w ${ATTRNAME} $CURSUM "$1"
-        case "$1" in
-    	    *.dmg|*.cdr|*.iso|*.sparseimage)
-    	        hdiutil checksum -type SHA1 "$1" ;;
-        esac
+
     elif [[ $setonly == false ]]; then
+	if [[ $verbose == true ]]; then echo -n "Checking: $1..."; fi
 	CURSUM=$(sha1 "$1")
+
 	if [[ $CURSUM != $CHKSUM ]]; then
-	    echo "Error: Checksum mismatch for $1: $CURSUM != $CHKSUM" \
-		> /dev/stderr
+	    if [[ $verbose == true ]]; then 
+		echo "FAILED"
+	    else
+		echo "FAILED:   $1"
+	    fi
+
 	    if [[ $force == true ]]; then
+		echo -n "CHANGING: $1..."
+
 		xattr -w ${ATTRNAME} $CURSUM "$1"
 		case "$1" in
     		    *.dmg|*.cdr|*.iso|*.sparseimage)
-    	                hdiutil checksum -type SHA1 "$1" ;;
+    	                hdiutil checksum -quiet -type SHA1 "$1" ;;
 		esac
+
+		echo "done"
 	    fi
 	    return 1
+
 	elif [[ $verbose == true ]]; then
-	    echo "Verified: $CHKSUM  $1"
+	    echo "done"
 	fi
     fi
     return 0
 }
 
+function is_archive_type()
+{
+    case "$1" in
+	*.zip)		     return 0 ;;
+	*.bz2|*.tbz)	     return 0 ;;
+	*.gz|*.tgz)	     return 0 ;;
+	*.rar)		     return 0 ;;
+	*.7z)		     return 0 ;;
+	*.dmg|*.sparseimage) return 0 ;;
+    esac
+
+    return 1
+}
+
 function validate_file() 
 {
-    if [[ $setonly == false ]]; then
-	case "$1" in
-	    *.zip)
-		if [[ $verbose == true ]]; then
-		    unzip -t "$1"
-		else
-		    unzip -qqt "$1"
-		fi ;;
-
-	    *.bz2|*.tbz)
-		if [[ $verbose == true ]]; then
-		    bzip2 -tv "$1"
-		else
-		    bzip2 -tq "$1"
-		fi ;;
-
-	    *.gz|*.tgz)
-		if [[ $verbose == true ]]; then
-		    gzip -tv "$1"
-		else
-		    gzip -tq "$1"
-		fi ;;
-
-	    *.rar)
-		unrar t "$1" ;;
-
-	    *.7z)
-		7za t "$1" ;;
-
-	    *.dmg|*.sparseimage)
-		if [[ $verbose == true ]]; then
-		    hdiutil verify "$1"
-		else
-		    hdiutil verify -quiet "$1"
-		fi ;;
-	esac
+    if [[ $setonly == true ]]; then
+	return 0
     fi
+
+    case "$1" in
+	*.zip)
+	    if [[ $veryverbose == true ]]; then
+		unzip -t "$1"
+	    else
+		unzip -qqt "$1"
+	    fi ;;
+
+	*.bz2|*.tbz)
+	    if [[ $veryverbose == true ]]; then
+		bzip2 -tv "$1"
+	    else
+		bzip2 -tq "$1"
+	    fi ;;
+
+	*.gz|*.tgz)
+	    if [[ $veryverbose == true ]]; then
+		gzip -tv "$1"
+	    else
+		gzip -tq "$1"
+	    fi ;;
+
+	*.rar)
+	    if [[ $veryverbose == true ]]; then
+		unrar t "$1"
+	    else
+		unrar t "$1" > /dev/null
+	    fi ;;
+
+	*.7z)
+	    if [[ $veryverbose == true ]]; then
+		7za t "$1"
+	    else
+		7za t "$1" > /dev/null
+	    fi ;;
+
+	*.dmg|*.sparseimage)
+	    if [[ $veryverbose == true ]]; then
+		hdiutil verify "$1"
+	    else
+		hdiutil verify -quiet "$1"
+	    fi ;;
+    esac
 }
 
 for file in "$@"; do
     name=$(basename "$file")
-    if [[ -d "$file" ]]; then
-	echo Verifying in directory $file ... > /dev/stderr
-    elif [[ -f "$file" && "$name" != ".DS_Store" && \
-	  "$name" != ".localized" ]]; then
+
+    if [[ -f "$file" && \
+	  "$name" != ".DS_Store" && "$name" != ".localized" ]]; then
+
 	if ! compare_checksum "$file"; then
 	    error=true
 	fi
-	if ! validate_file "$file"; then
-	    error=true
+
+	if is_archive_type "$file"; then
+	    if [[ $verbose == true ]]; then echo -n "Testing:  $file..."; fi
+
+	    if ! validate_file "$file"; then
+		if [[ $verbose == true ]]; then 
+		    echo "FAILED"
+		else
+		    echo "INVALID:  $file"
+		fi
+		error=true
+	    elif [[ $verbose == true ]]; then 
+		echo "done"; 
+	    fi
 	fi
     fi
 done
