changes

diff --git a/verify b/verify
--- a/verify
+++ b/verify
@@ -3,6 +3,10 @@
 # verify, version 1.0
 #   by John Wiegley <johnw@newartisans.com>
 
+function sha1() {
+    openssl sha1 "$1" | sed 's/.*= //'
+}
+
 if [[ -z "$1" ]]; then
     echo "usage: verify [OPTIONS] <FILE ...>"
     echo "options:"
@@ -12,21 +16,21 @@ if [[ -z "$1" ]]; then
     exit 1
 fi
 
-ATTRNAME=checksum
+export ATTRNAME=checksum-sha1
 
-verbose=false
-setonly=false
-force=false
+export verbose=false
+export setonly=false
+export force=false
 
 while [[ "${1:0:1}" == "-" ]]; do
     if [[ "$1" == "-v" ]]; then
-        verbose=true
+        export verbose=true
         shift 1
     elif [[ "$1" == "-s" ]]; then
-        setonly=true
+        export setonly=true
         shift 1
     elif [[ "$1" == "-f" ]]; then
-        force=true
+        export force=true
         shift 1
     else
 	break
@@ -35,32 +39,39 @@ done
 
 error=false
 
+function compare_checksum() 
+{
+    CHKSUM=$(xattr -p ${ATTRNAME} "$1" 2> /dev/null)
+    if [[ -z "$CHKSUM" ]]; then
+	if [[ $verbose == true || $setonly == true ]]; then
+	    echo "Note: No existing checksum for $1, setting..."
+	fi
+	CURSUM=$(sha1 "$1")
+	xattr -w ${ATTRNAME} $CURSUM "$1"
+    elif [[ $setonly == false ]]; then
+	CURSUM=$(sha1 "$1")
+	if [[ $CURSUM != $CHKSUM ]]; then
+	    echo "Error: Checksum mismatch for $1: $CURSUM != $CHKSUM" \
+		> /dev/stderr
+	    if [[ $force == true ]]; then
+		xattr -w ${ATTRNAME} $CURSUM "$1"
+	    fi
+	    return 1
+	elif [[ $verbose == true ]]; then
+	    echo "Verified: $CHKSUM  $1"
+	fi
+    fi
+    return 0
+}
+
 for file in "$@"; do
     name=$(basename "$file")
     if [[ -d "$file" ]]; then
-	echo Verifying in directory $file ...
+	echo Verifying in directory $file ... > /dev/stderr
     elif [[ -f "$file" && "$name" != ".DS_Store" && \
 	  "$name" != ".localized" ]]; then
-	CHKSUM=$(xattr -p $ATTRNAME "$file" 2> /dev/null)
-	if [[ -z "$CHKSUM" ]]; then
-	    if [[ $verbose == true || $setonly == true ]]; then
-		echo "Note: No existing checksum for $file, setting..."
-	    fi
-	    CURSUM=$(md5 -q "$file")
-	    xattr -w $ATTRNAME $CURSUM "$file"
-	    CHKSUM=$CURSUM
-	elif [[ $setonly == false ]]; then
-	    CURSUM=$(md5 -q "$file")
-	    if [[ $CURSUM != $CHKSUM ]]; then
-		echo "Error: Checksum mismatch for $file: $CURSUM != $CHKSUM" \
-		    > /dev/stderr
-		error=true
-		if [[ $force == true ]]; then
-		    xattr -w $ATTRNAME $CURSUM "$file"
-		fi
-	    elif [[ $verbose == true ]]; then
-		echo "Verified: $CHKSUM  $file"
-	    fi
+	if ! compare_checksum "$file"; then
+	    error=true
 	fi
     fi
 done
