changes

diff --git a/whither b/whither
--- a/whither
+++ b/whither
@@ -7,7 +7,11 @@ if [[ $# -ne 1 ]]; then
     exit 1
 fi
 
-path=$(which "$1") || { echo "whither: $1 not found" >&2; exit 1; }
+if [[ -e "$1" ]]; then
+    path=$1
+else
+    path=$(which "$1") || { echo "whither: $1 not found" >&2; exit 1; }
+fi
 
 echo "$path"
 
